name: env-megadetector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - megadetector==10.0.3
      - ultralytics==8.3.177
      # speciesnet is installed separately, see python code 